/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mapsko.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    grass011: THREE.Mesh
    grass011_1: THREE.Mesh
    grass011_2: THREE.Mesh
    grass011_3: THREE.Mesh
    grass011_4: THREE.Mesh
    grass011_5: THREE.Mesh
    grass011_6: THREE.Mesh
    grass011_7: THREE.Mesh
    grass011_8: THREE.Mesh
    grass011_9: THREE.Mesh
    grass011_10: THREE.Mesh
    grass011_11: THREE.Mesh
    grass011_12: THREE.Mesh
    grass011_13: THREE.Mesh
    grass011_14: THREE.Mesh
    grass011_15: THREE.Mesh
    grass011_16: THREE.Mesh
    grass011_17: THREE.Mesh
    grass011_18: THREE.Mesh
    grass011_19: THREE.Mesh
    grass011_20: THREE.Mesh
    grass011_21: THREE.Mesh
  }
  materials: {
    ['colormap.010']: THREE.MeshStandardMaterial
    colormap: THREE.MeshStandardMaterial
    ['colormap.001']: THREE.MeshStandardMaterial
    ['colormap.002']: THREE.MeshStandardMaterial
    ['colormap.003']: THREE.MeshStandardMaterial
    ['colormap.004']: THREE.MeshStandardMaterial
    ['colormap.005']: THREE.MeshStandardMaterial
    ['colormap.006']: THREE.MeshStandardMaterial
    ['colormap.008']: THREE.MeshStandardMaterial
    ['colormap.011']: THREE.MeshStandardMaterial
    ['colormap.012']: THREE.MeshStandardMaterial
    ['colormap.013']: THREE.MeshStandardMaterial
    ['colormap.014']: THREE.MeshStandardMaterial
    ['colormap.015']: THREE.MeshStandardMaterial
    ['colormap.016']: THREE.MeshStandardMaterial
    ['colormap.017']: THREE.MeshStandardMaterial
    ['colormap.018']: THREE.MeshStandardMaterial
    ['colormap.019']: THREE.MeshStandardMaterial
    ['colormap.020']: THREE.MeshStandardMaterial
    ['colormap.021']: THREE.MeshStandardMaterial
    ['colormap.023']: THREE.MeshStandardMaterial
    ['colormap.024']: THREE.MeshStandardMaterial
  }
  //animations: GLTFAction[]
}

// @ts-ignore
export function Mapsko(props: JSX.IntrinsicElements['group']) {
const { nodes, materials } = useGLTF('/mapsko.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.grass011.geometry} material={materials['colormap.010']} />
      <mesh geometry={nodes.grass011_1.geometry} material={materials.colormap} />
      <mesh geometry={nodes.grass011_2.geometry} material={materials['colormap.001']} />
      <mesh geometry={nodes.grass011_3.geometry} material={materials['colormap.002']} />
      <mesh geometry={nodes.grass011_4.geometry} material={materials['colormap.003']} />
      <mesh geometry={nodes.grass011_5.geometry} material={materials['colormap.004']} />
      <mesh geometry={nodes.grass011_6.geometry} material={materials['colormap.005']} />
      <mesh geometry={nodes.grass011_7.geometry} material={materials['colormap.006']} />
      <mesh geometry={nodes.grass011_8.geometry} material={materials['colormap.008']} />
      <mesh geometry={nodes.grass011_9.geometry} material={materials['colormap.011']} />
      <mesh geometry={nodes.grass011_10.geometry} material={materials['colormap.012']} />
      <mesh geometry={nodes.grass011_11.geometry} material={materials['colormap.013']} />
      <mesh geometry={nodes.grass011_12.geometry} material={materials['colormap.014']} />
      <mesh geometry={nodes.grass011_13.geometry} material={materials['colormap.015']} />
      <mesh geometry={nodes.grass011_14.geometry} material={materials['colormap.016']} />
      <mesh geometry={nodes.grass011_15.geometry} material={materials['colormap.017']} />
      <mesh geometry={nodes.grass011_16.geometry} material={materials['colormap.018']} />
      <mesh geometry={nodes.grass011_17.geometry} material={materials['colormap.019']} />
      <mesh geometry={nodes.grass011_18.geometry} material={materials['colormap.020']} />
      <mesh geometry={nodes.grass011_19.geometry} material={materials['colormap.021']} />
      <mesh geometry={nodes.grass011_20.geometry} material={materials['colormap.023']} />
      <mesh geometry={nodes.grass011_21.geometry} material={materials['colormap.024']} />
    </group>
  )
}

useGLTF.preload('/mapsko.glb')
