/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mapsko.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import React, { useLayoutEffect } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    grass011: THREE.Mesh
    grass011_1: THREE.Mesh
    grass011_2: THREE.Mesh
    grass011_3: THREE.Mesh
    grass011_4: THREE.Mesh
    grass011_5: THREE.Mesh
    grass011_6: THREE.Mesh
    grass011_7: THREE.Mesh
    grass011_8: THREE.Mesh
    grass011_9: THREE.Mesh
    grass011_10: THREE.Mesh
    grass011_11: THREE.Mesh
    grass011_12: THREE.Mesh
    grass011_13: THREE.Mesh
    grass011_14: THREE.Mesh
    grass011_15: THREE.Mesh
    grass011_16: THREE.Mesh
    grass011_17: THREE.Mesh
    grass011_18: THREE.Mesh
    grass011_19: THREE.Mesh
    grass011_20: THREE.Mesh
    grass011_21: THREE.Mesh
  }
  materials: {
    ['colormap.010']: THREE.MeshStandardMaterial
    colormap: THREE.MeshStandardMaterial
    ['colormap.001']: THREE.MeshStandardMaterial
    ['colormap.002']: THREE.MeshStandardMaterial
    ['colormap.003']: THREE.MeshStandardMaterial
    ['colormap.004']: THREE.MeshStandardMaterial
    ['colormap.005']: THREE.MeshStandardMaterial
    ['colormap.006']: THREE.MeshStandardMaterial
    ['colormap.008']: THREE.MeshStandardMaterial
    ['colormap.011']: THREE.MeshStandardMaterial
    ['colormap.012']: THREE.MeshStandardMaterial
    ['colormap.013']: THREE.MeshStandardMaterial
    ['colormap.014']: THREE.MeshStandardMaterial
    ['colormap.015']: THREE.MeshStandardMaterial
    ['colormap.016']: THREE.MeshStandardMaterial
    ['colormap.017']: THREE.MeshStandardMaterial
    ['colormap.018']: THREE.MeshStandardMaterial
    ['colormap.019']: THREE.MeshStandardMaterial
    ['colormap.020']: THREE.MeshStandardMaterial
    ['colormap.021']: THREE.MeshStandardMaterial
    ['colormap.023']: THREE.MeshStandardMaterial
    ['colormap.024']: THREE.MeshStandardMaterial
  }
  //animations: GLTFAction[]
}

// @ts-ignore
export const Mapsko = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { scene, nodes: _nodes, materials: _materials } = useGLTF('/mapsko.glb') as unknown as GLTFResult

  useLayoutEffect(() => {
    scene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true;    
        child.receiveShadow = true; 
      }
    });
  }, [scene]);


  return <primitive object={scene} {...props} ref={ref} />
})

useGLTF.preload('/mapsko.glb')

