/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/chopstick.glb -t 
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    chopstick_1: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export const Wand = forwardRef<THREE.Group, React.JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/chopstick.glb') as unknown as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.chopstick_1.geometry} material={materials.colormap} />
    </group>
  )
})

useGLTF.preload('/chopstick.glb')